// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPsi6jJzZpN78eR6utYfVK7gcRZwH_VUQ',
    appId: '1:92985170356:web:f1195e31016993917d7ae1',
    messagingSenderId: '92985170356',
    projectId: 'gradproject-25fb2',
    authDomain: 'gradproject-25fb2.firebaseapp.com',
    storageBucket: 'gradproject-25fb2.appspot.com',
    measurementId: 'G-PQCE3QJY70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmSFHNf1wX37sI50LsMlHBHoLvnfZZjl0',
    appId: '1:92985170356:android:5f08d5af59af67a37d7ae1',
    messagingSenderId: '92985170356',
    projectId: 'gradproject-25fb2',
    storageBucket: 'gradproject-25fb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-hbGecjxvV1AAcZg9ZECwTlfvcZi8H90',
    appId: '1:92985170356:ios:9e84602d628b9dc97d7ae1',
    messagingSenderId: '92985170356',
    projectId: 'gradproject-25fb2',
    storageBucket: 'gradproject-25fb2.appspot.com',
    iosBundleId: 'com.example.graduationApp',
  );

}