// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu-6Qz-EAe0__r_PQeDyKffNS6ksHT3Dg',
    appId: '1:752084190116:web:01065f9864287820a5b731',
    messagingSenderId: '752084190116',
    projectId: 'graduationproject-17ddb',
    authDomain: 'graduationproject-17ddb.firebaseapp.com',
    storageBucket: 'graduationproject-17ddb.appspot.com',
    measurementId: 'G-MWHMLDEXX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_444FpfpAqBCJFdpTJXLsTl7cH8sqdA',
    appId: '1:752084190116:android:d2448d83b4cbfc3ba5b731',
    messagingSenderId: '752084190116',
    projectId: 'graduationproject-17ddb',
    storageBucket: 'graduationproject-17ddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwYF6f9H2TNt6aQAxRjns6CM61mHtxhtA',
    appId: '1:752084190116:ios:16479204b8306939a5b731',
    messagingSenderId: '752084190116',
    projectId: 'graduationproject-17ddb',
    storageBucket: 'graduationproject-17ddb.appspot.com',
    iosBundleId: 'com.example.graduationApp',
  );
}
