// Generated by Flutter Assets

// ignore_for_file: unused_field, camel_case_types, non_constant_identifier_names, library_private_types_in_public_api

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
        
class Assets extends StatelessWidget {
  final AssetsData assets;
  final Widget child;

  const Assets({
    super.key,
    required this.assets,
    required this.child,
  });

  static AssetsData of(BuildContext context) {
    final widget = context.dependOnInheritedWidgetOfExactType<_InheritedAssets>();
    return widget?.assets ?? AssetsData.light();
  }

  @override
  Widget build(BuildContext context) {
    return _InheritedAssets(
      assets: assets,
      child: child,
    );
  }
}

class _InheritedAssets extends InheritedWidget {
  final AssetsData assets;

  const _InheritedAssets({
    required this.assets,
    required super.child,
  });

  @override
  bool updateShouldNotify(covariant _InheritedAssets oldWidget) => assets != oldWidget.assets;
}

class AssetsData {
  static AssetsData? _light;
  static AssetsData? _dark;

  factory AssetsData.light() => _light ??= AssetsData._(brightness: Brightness.light);
  factory AssetsData.dark() => _dark ??= AssetsData._(brightness: Brightness.dark);
  factory AssetsData.brightness(Brightness brightness) => brightness == Brightness.light ? AssetsData.light() : AssetsData.dark();

  final Brightness _brightness;

  AssetsData._({
    required Brightness brightness,
  })  : _brightness = brightness,
        fonts = _assets_fonts_dart._(brightness: brightness),
        icons = _assets_icons_dart._(brightness: brightness),
        images = _assets_images_dart._(brightness: brightness);

  final _assets_fonts_dart fonts;
  final _assets_icons_dart icons;
  final _assets_images_dart images;
}

class _assets_fonts_dart {
  final Brightness _brightness;

  _assets_fonts_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final Inter_Regular_ttf = 'assets/fonts/Inter-Regular.ttf';
}

class _assets_icons_dart {
  final Brightness _brightness;

  _assets_icons_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final adjustments_svg = 'assets/icons/adjustments.svg';
  final calendar_png = 'assets/icons/calendar.png';
  final calendar_svg = 'assets/icons/calendar.svg';
  final chat_alt_png = 'assets/icons/chat-alt.png';
  final chat_alt_svg = 'assets/icons/chat-alt.svg';
  final dots_horizontal_png = 'assets/icons/dots-horizontal.png';
  final dots_horizontal_svg = 'assets/icons/dots-horizontal.svg';
  final facebook_png = 'assets/icons/facebook.png';
  final facebook_svg = 'assets/icons/facebook.svg';
  final google_png = 'assets/icons/google.png';
  final google_svg = 'assets/icons/google.svg';
  final home_png = 'assets/icons/home.png';
  final home_svg = 'assets/icons/home.svg';
  final Reminder_png = 'assets/icons/Reminder.png';
  final Reminder_svg = 'assets/icons/Reminder.svg';
  final visa_svg = 'assets/icons/visa.svg';
}

class _assets_images_dart {
  final Brightness _brightness;

  _assets_images_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final drimage_png = 'assets/images/drimage.png';
  final Logo_png = 'assets/images/Logo.png';
  final Scan_png = 'assets/images/Scan.png';
  final Scan_svg = 'assets/images/Scan.svg';
}
